name: Build wheels AND Upload Python Package

on:
  release:
    types: [published]
  push:
    tags:
    - '*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os:
          - name: "ubuntu-24.04"
            platform: "linux"
            platform_id: "manylinux_x86_64"

          - name: "ubuntu-24.04-arm"
            platform: "linux"
            platform_id: "manylinux_aarch64"

          - name: "macos-14"
            platform: "macos"
            min_macos_version: "14"
            platform_id: "macosx_arm64"

          - name: "windows-2025"
            platform: "windows"
            platform_id: "win_amd64"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up QEMU
        if: runner.os == 'Linux' && runner.arch == 'X64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          # 1. Enable PyPy builds (Required in v3+)
          CIBW_ENABLE: pypy
          # 2. Configure Architectures
          CIBW_ARCHS_LINUX: ${{ runner.arch == 'X64' && 'auto ppc64le s390x' || 'auto armv7l' }}
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          # SKIP ALL FREE-THREADING BUILDS (t-suffix)
          CIBW_SKIP: "*t-*"
          # 3. Build & Test Settings
          CIBW_TEST_REQUIRES: tox
          CIBW_TEST_COMMAND: cd {project} && tox
          CIBW_TEST_SKIP: "*"
          CIBW_BUILD_VERBOSITY: 1

      - name: Store wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os.name }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "dist/*.whl"
          generateReleaseNotes: true

      - name: Publish wheels to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
